Account==Account
Display name==Display name
Active accounts==Active accounts
Unix uid==Unix uid
WINDOWS directory==WINDOWS directory
UNIX directory==UNIX directory
Groups==Groups
Expiration date==Expiration date
Creation date==Creation date
Last logon date==Last logon date
Status==Status
Selected==Selected
Single ADD==Single ADD
Multi ADD==Multi ADD
Active accounts==Active accounts
Expired accounts==Expired accounts
Locked accounts==Locked accounts
Logout==Logout
Delete==Delete
Lock for 30 days==Lock for 30 days
Lock==Lock
Unlock==Unlock
Are you sure you want to delete all selected users from Active Directory?==Are you sure you want to delete all selected users from Active Directory?
Are you sure you want to block all selected users in 30 days in Active Directory?==Are you sure you want to block all selected users in 30 days in Active Directory?
Are you sure you want to lock all selected users in Active Directory?==Are you sure you want to lock all selected users in Active Directory?
Are you sure you want to unlock all selected users in Active Directory?==Are you sure you want to unlock all selected users in Active Directory?
Connection problem...==Connection problem...
Failed as admin ...==Failed as admin ...
The data returned by the LDAP server is incorrect.==The data returned by the LDAP server is incorrect.
Error while connecting to the LDAP server.==Error while connecting to the LDAP server.

