Account==Konto
Display name==Nazwa wyświetlana
Active accounts==Aktywne konta
Unix uid==Unix uid
WINDOWS directory==katalog WINDOWS
UNIX directory==katalog UNIX
Groups==Grupy
Expiration date==Data blokady
Creation date==Data utworzenia
Last logon date==Ostatnie logowanie
Status==Status
Selected==Zaznaczeni
Single ADD==Dodaj jednego
Multi ADD==Dodaj wiele
Active accounts==Aktywne konta
Expired accounts==Z datą przeterminowanie
Locked accounts==Zablokowane konta
Logout==Wyloguj
Delete==Usuń
Lock for 30 days==Blokuj za 30 dni
Lock==Zablokuj
Unlock==Odblokuj
Are you sure you want to delete all selected users from Active Directory?==Czy jesteś pewien że chcesz usunąć wszystkich zaznaczonych użytkowników z Active Directory?
Are you sure you want to block all selected users in 30 days in Active Directory?==Czy jeśteś pewien że chcesz zablokować zaznaczonych za 30 dni w Active Directory?
Are you sure you want to lock all selected users in Active Directory?==Czy jesteś pewien że chcesz zablokować zaznaczonych użytkowników w Active Directory?
Are you sure you want to unlock all selected users in Active Directory?==Czy jesteś pewien że chcesz odblokować zaznaczonych w Active Directory?
Connection problem...==Problem z połączeniem...
Failed as admin ...==Nie udało się jako admin ...
The data returned by the LDAP server is incorrect.==Dane zwrócone przez serwer LDAP są niepoprawne.
Error while connecting to the LDAP server.==Problem z połączeniem z serwerem LDAP.
Search result==Wynik wyszukania
found==znaleziono
perons==osoby
Welcome to the Active Directory management support system==Witaj w systemie wspomagania zarządzaniem Active Directory
Select the action from the menu at the top of the page.==Wybierz czynność z menu u góry strony.
Objects:==Objektów:
Active persons:==Aktywnych użytkowników:
Active Directory tree statistics:==Statystyka drzewa Active Directory:
Locked persons:==Zablokowanych użytkowników:
With expiration date persons:==Użytkowników z datą przeterminowania:
Computers:==Komputerów:
Groups:==Grup:
Please LogIn==Proszę zaloguj się
User==Użytkownik
Password==Hasło
Login==Zaloguj
Login error!==Błąd logowania!

